config/routes.rb
Rails.application.routes.draw do
  resources :tweeets
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweeets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweeets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image_url,:bio])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:image_url,:bio])

  end

  def show

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :bio, :email, :password, :image_url, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :bio, :email, :password, :image_url, :password_confirmation, :current_password)
  end
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tweeets
  # GET /tweeets.json
  def index
    @tweeets = Tweeet.all
  end

  # GET /tweeets/1
  # GET /tweeets/1.json
  def show

  end

  # GET /tweeets/new
  def new
    @tweeet = current_user.tweeets.build
#    @tweeet = Tweeet.new
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets
  # POST /tweeets.json
  def create
#    @tweeet = Tweeet.new(tweeet_params)
    @tweeet = current_user.tweeets.build(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully created.' }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1
  # PATCH/PUT /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1
  # DELETE /tweeets/1.json
  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: 'Tweeet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/home/index.html.erb
<h1>Profile Page</h1>
  <p>Name: <%= current_user.name %><br><br>
    Email: <%= current_user.email %><br><br>
    Bio: <%= current_user.bio %><br><br>
    Image: <img src="<%= current_user.image_url %>" width="125px" height="125px" alt="<%= current_user.name %>">
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseAssignmentScott</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <div = "navbar">
      <ul>
        <li>
          <%= link_to('profile', root_url) %>
        </li>
      <% if user_signed_in? %>
        <li>
      <%= link_to('edit profile', edit_user_registration_url) %>
        </li>
        <li>
      <%= link_to('sign out', destroy_user_session_url, method: :delete) %>
        </li>
        <li>
          Hello <%= current_user.name %>! Your email: <%= current_user.email %>. Your user id: <%= current_user.id %>
        </li>


      <% else %>
        <li>
          <%= link_to('sign in', new_user_session_url) %>
        </li>
        <li>
          <%= link_to('sign up', new_user_registration_url) %>
        </li>
      <% end %>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tweeets/_form.html.erb
<%= form_with(model: tweeet, local: true) do |form| %>
  <% if tweeet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweeet.errors.count, "error") %> prohibited this tweeet from being saved:</h2>

      <ul>
      <% tweeet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tweeet %>
    <%= form.text_area :tweeet %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweeets/edit.html.erb
<h1>Editing Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Show', @tweeet %> |
<%= link_to 'Back', tweeets_path %>

app/views/tweeets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profile Page</h1>
  <p>Name: <%= current_user.name %><br><br>
    Email: <%= current_user.email %><br><br>
    Bio: <%= current_user.bio %><br><br>
    Image: <img src="<%= current_user.image_url %>" width="125px" height="125px" alt="<%= current_user.name %>">
  </p>
<br><br>
<h1>Tweeets</h1><br><br>

<table>
  <thead>
    <tr>
      <th>Tweeet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweeets.each do |tweeet| %>
      <tr>
        <td width="300px"><%= tweeet.tweeet %></td>
        <td width="200px"><b>written by</b>
          <% if user_signed_in? == true && current_user.name == tweeet.user.name %>
          <%= link_to current_user.name, edit_user_registration_url %>
          <% else %><i><%= tweeet.user.name %><i>
          <% end %>
        </td>

        <td width="50px">
          <% if user_signed_in? == true && current_user.name == tweeet.user.name %>
          <%= link_to 'Edit', edit_tweeet_path(tweeet) %>
          <% end %>
        </td>
        <td width="50px">
          <% if user_signed_in? == true && current_user.name == tweeet.user.name %>
          <%= link_to 'Destroy', tweeet, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweeet', new_tweeet_path %>

app/views/tweeets/new.html.erb
<h1>New Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweeet:</strong>
  <%= @tweeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>